# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdbdca0cbdf6ecd280b77da3d81d48700efc370508efd238038f29ad13a58bfa5402e980c4906a8edb3dd26c9e4bb8ea4c94130ea82e56576803afd2e0034a8c

test:
  secret_key_base: d36835b99742c82f90a054a559192a08981b9e29430113ce7977b34e6a9e20fbd201c65bf5359051cb5b49013f2bcb39c04fd7719e03c15ea1f392b7d17bdfa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
